# This file is part of the HörTech Open Master Hearing Aid (openMHA)
# Copyright © 2014 2017 2018 HörTech gGmbH
#
# openMHA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# openMHA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License, version 3 for more details.
#
# You should have received a copy of the GNU Affero General Public License,
# version 3 along with openMHA.  If not, see <http://www.gnu.org/licenses/>.

include ../plugin.mk
#CFLAGS+="-std=gnu99"
#$(BUILD_DIR)/rnndenoise$(PLUGIN_EXT): $(BUILD_DIR)/celt_lpc.o $(BUILD_DIR)/denoise.o $(BUILD_DIR)/kiss_fft.o $(BUILD_DIR)/pitch.o $(BUILD_DIR)/rnn_data.o $(BUILD_DIR)/rnn_reader.o $(BUILD_DIR)/rnn.o
LDFLAGS += librnnoise.a

# Local Variables:
# compile-command: "make"
# coding: utf-8-unix
# End:
